// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models
{
    public partial class MessageUser
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public int ReceiveId { get; set; }
        public string Message { get; set; }
        public DateTime? TimeSend { get; set; }

        public virtual Account Receive { get; set; }
        public virtual Account Sender { get; set; }
    }
}